--https://gist.github.com/voskobovich/43f851859c23a8261514
--CURRENCY
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('England (United Kingdom)', 'Pounds', 'GBP', '£');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Albania', 'Leke', 'ALL', 'Lek');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('America', 'Dollars', 'USD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Afghanistan', 'Afghanis', 'AFN', '؋');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Argentina', 'Pesos', 'ARS', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Aruba', 'Guilders', 'AWG', 'ƒ');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Australia', 'Dollars', 'AUD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Azerbaijan', 'New Manats', 'AZN', 'ман');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Bahamas', 'Dollars', 'BSD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Barbados', 'Dollars', 'BBD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Belarus', 'Rubles', 'BYR', 'p.');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Belgium', 'Euro', 'EUR', '€');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Beliz', 'Dollars', 'BZD', 'BZ$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Bermuda', 'Dollars', 'BMD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Bolivia', 'Bolivianos', 'BOB', '$b');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Bosnia and Herzegovina', 'Convertible Marka', 'BAM', 'KM');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Botswana', 'Pula', 'BWP', 'P');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Bulgaria', 'Leva', 'BGN', 'лв');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Brazil', 'Reais', 'BRL', 'R$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Britain (United Kingdom)', 'Pounds', 'GBP', '£');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Brunei Darussalam', 'Dollars', 'BND', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Cambodia', 'Riels', 'KHR', '៛');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Canada', 'Dollars', 'CAD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Cayman Islands', 'Dollars', 'KYD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Chile', 'Pesos', 'CLP', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('China', 'Yuan Renminbi', 'CNY', '¥');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Colombia', 'Pesos', 'COP', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Costa Rica', 'Colón', 'CRC', '₡');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Croatia', 'Kuna', 'HRK', 'kn');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Cuba', 'Pesos', 'CUP', '₱');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Cyprus', 'Euro', 'EUR', '€');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Czech Republic', 'Koruny', 'CZK', 'Kč');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Denmark', 'Kroner', 'DKK', 'kr');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Dominican Republic', 'Pesos', 'DOP ', 'RD$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('East Caribbean', 'Dollars', 'XCD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Egypt', 'Pounds', 'EGP', '£');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('El Salvador', 'Colones', 'SVC', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Euro', 'Euro', 'EUR', '€');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Falkland Islands', 'Pounds', 'FKP', '£');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Fiji', 'Dollars', 'FJD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('France', 'Euro', 'EUR', '€');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Ghana', 'Cedis', 'GHC', '¢');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Gibraltar', 'Pounds', 'GIP', '£');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Greece', 'Euro', 'EUR', '€');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Guatemala', 'Quetzales', 'GTQ', 'Q');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Guernsey', 'Pounds', 'GGP', '£');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Guyana', 'Dollars', 'GYD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Holland (Netherlands)', 'Euro', 'EUR', '€');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Honduras', 'Lempiras', 'HNL', 'L');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Hong Kong', 'Dollars', 'HKD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Hungary', 'Forint', 'HUF', 'Ft');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Iceland', 'Kronur', 'ISK', 'kr');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('India', 'Rupees', 'INR', 'Rp');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Indonesia', 'Rupiahs', 'IDR', 'Rp');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Iran', 'Rials', 'IRR', '﷼');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Ireland', 'Euro', 'EUR', '€');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Isle of Man', 'Pounds', 'IMP', '£');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Israel', 'New Shekels', 'ILS', '₪');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Italy', 'Euro', 'EUR', '€');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Jamaica', 'Dollars', 'JMD', 'J$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Japan', 'Yen', 'JPY', '¥');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Jersey', 'Pounds', 'JEP', '£');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Kazakhstan', 'Tenge', 'KZT', 'лв');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Korea (North)', 'Won', 'KPW', '₩');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Korea (South)', 'Won', 'KRW', '₩');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Kyrgyzstan', 'Soms', 'KGS', 'лв');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Laos', 'Kips', 'LAK', '₭');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Latvia', 'Lati', 'LVL', 'Ls');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Lebanon', 'Pounds', 'LBP', '£');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Liberia', 'Dollars', 'LRD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Liechtenstein', 'Switzerland Francs', 'CHF', 'CHF');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Lithuania', 'Litai', 'LTL', 'Lt');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Luxembourg', 'Euro', 'EUR', '€');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Macedonia', 'Denars', 'MKD', 'ден');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Malaysia', 'Ringgits', 'MYR', 'RM');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Malta', 'Euro', 'EUR', '€');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Mauritius', 'Rupees', 'MUR', '₨');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Mexico', 'Pesos', 'MXN', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Mongolia', 'Tugriks', 'MNT', '₮');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Mozambique', 'Meticais', 'MZN', 'MT');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Namibia', 'Dollars', 'NAD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Nepal', 'Rupees', 'NPR', '₨');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Netherlands Antilles', 'Guilders', 'ANG', 'ƒ');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Netherlands', 'Euro', 'EUR', '€');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('New Zealand', 'Dollars', 'NZD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Nicaragua', 'Cordobas', 'NIO', 'C$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Nigeria', 'Nairas', 'NGN', '₦');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('North Korea', 'Won', 'KPW', '₩');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Norway', 'Krone', 'NOK', 'kr');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Oman', 'Rials', 'OMR', '﷼');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Pakistan', 'Rupees', 'PKR', '₨');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Panama', 'Balboa', 'PAB', 'B/.');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Paraguay', 'Guarani', 'PYG', 'Gs');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Peru', 'Nuevos Soles', 'PEN', 'S/.');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Philippines', 'Pesos', 'PHP', 'Php');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Poland', 'Zlotych', 'PLN', 'zł');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Qatar', 'Rials', 'QAR', '﷼');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Romania', 'New Lei', 'RON', 'lei');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Russia', 'Rubles', 'RUB', 'руб');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Saint Helena', 'Pounds', 'SHP', '£');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Saudi Arabia', 'Riyals', 'SAR', '﷼');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Serbia', 'Dinars', 'RSD', 'Дин.');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Seychelles', 'Rupees', 'SCR', '₨');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Singapore', 'Dollars', 'SGD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Slovenia', 'Euro', 'EUR', '€');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Solomon Islands', 'Dollars', 'SBD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Somalia', 'Shillings', 'SOS', 'S');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('South Africa', 'Rand', 'ZAR', 'R');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('South Korea', 'Won', 'KRW', '₩');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Spain', 'Euro', 'EUR', '€');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Sri Lanka', 'Rupees', 'LKR', '₨');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Sweden', 'Kronor', 'SEK', 'kr');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Switzerland', 'Francs', 'CHF', 'CHF');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Suriname', 'Dollars', 'SRD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Syria', 'Pounds', 'SYP', '£');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Taiwan', 'New Dollars', 'TWD', 'NT$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Thailand', 'Baht', 'THB', '฿');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Trinidad and Tobago', 'Dollars', 'TTD', 'TT$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Turkey', 'Lira', 'TRY', 'TL');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Turkey', 'Liras', 'TRL', '£');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Tuvalu', 'Dollars', 'TVD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Ukraine', 'Hryvnia', 'UAH', '₴');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('United Kingdom', 'Pounds', 'GBP', '£');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('United States of America', 'Dollars', 'USD', '$');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Uruguay', 'Pesos', 'UYU', '$U');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Uzbekistan', 'Sums', 'UZS', 'лв');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Vatican City', 'Euro', 'EUR', '€');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Venezuela', 'Bolivares Fuertes', 'VEF', 'Bs');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Vietnam', 'Dong', 'VND', '₫');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Yemen', 'Rials', 'YER', '﷼');
INSERT INTO currency (county, currency, abv, currencySymbol) VALUES ('Zimbabwe', 'Zimbabwe Dollars', 'ZWD', 'Z$');

-- CATEGORY

INSERT INTO category VALUES(1, "Food", "ic_cutlery.png");
INSERT INTO category VALUES(2, "Groceries", "ic_cart.png");
INSERT INTO category VALUES(3, "Utilities", "ic_tool.png");
INSERT INTO category VALUES(4, "Entertainment", "ic_glass.png");
INSERT INTO category VALUES(5, "Housing", "ic_mortgage.png");
INSERT INTO category VALUES(6, "Transportation", "ic_transport.png");
INSERT INTO category VALUES(7, "Clothing", "ic_shirt.png");
INSERT INTO category VALUES(8, "Insurance", "ic_mortgage.png");
INSERT INTO category VALUES(9, "Health", "ic_medicine.png");
INSERT INTO category VALUES(10, "Tax", "ic_tax.png");
INSERT INTO category VALUES(11, "Education", "ic_school.png");
INSERT INTO category VALUES(12, "Work", "ic_briefcase.png");
INSERT INTO category VALUES(13, "Others", "ic_briefcase.png");
INSERT INTO category VALUES(14, "Donations", "ic_others.png");


--ACCOUNT
INSERT INTO accountDatabase VALUES(1, "Main Account", "pyramid.jpg", 1, 1);
INSERT INTO accountDatabase VALUES(2, "Wallet", "pyramid.jpg", 1, 0);
